

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank Accounts Microservice"
  contactDetails:
    name: "Ashish Higgins"
    email: "ashish@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-5678