
build:
  version: "3.0"

loans:
    message: "Welcome to EazyBank Loans Microservice"
    contactDetails:
        name: "Ashish Higgins"
        email: "ashishhiggins10@gmail.com"
    onCallSupport:
        - (555) 555-1234
        - (555) 555-5678