spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ashishhiggins/eazybytes-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
      #        native:

#          search-locations: "file:///C://Users//ashis//spring-cloud-configurations//config"
#          search-locations: "classpath:/config"\

  rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
encrypt:
  key: "79KSLJHG9344W6THW7T8YHJGK"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true



